CREATE TABLE IF NOT EXISTS `ai_custom_query_scheme` (
  `id` bigint NOT NULL COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
  `config_key` varchar(64) NOT NULL COMMENT 'CRUD配置键',
  `scheme_name` varchar(128) NOT NULL COMMENT '查询方案名称',
  `conditions_json` json DEFAULT NULL COMMENT '查询条件JSON',
  `columns_json` json DEFAULT NULL COMMENT '展示字段JSON',
  `sort_json` json DEFAULT NULL COMMENT '排序配置JSON',
  `display_json` json DEFAULT NULL COMMENT '展示方式配置JSON',
  `is_default` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否默认方案（1是 0否）',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
  `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_config_user` (`tenant_id`, `config_key`, `create_by`),
  KEY `idx_tenant_config_default` (`tenant_id`, `config_key`, `create_by`, `is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI自定义查询方案表';
