-- =============================================
-- AI 大屏生成记录
-- =============================================

CREATE TABLE IF NOT EXISTS `ai_dashboard_generate_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `session_id` varchar(80) DEFAULT NULL COMMENT 'AI会话ID',
  `project_id` bigint DEFAULT NULL COMMENT '大屏项目ID',
  `project_name` varchar(128) DEFAULT NULL COMMENT '大屏项目名称',
  `business_definition_id` bigint DEFAULT NULL COMMENT '业务定义ID',
  `business_name` varchar(128) DEFAULT NULL COMMENT '业务定义名称',
  `provider_id` bigint DEFAULT NULL COMMENT 'AI供应商ID',
  `provider_name` varchar(128) DEFAULT NULL COMMENT 'AI供应商名称',
  `model_name` varchar(128) DEFAULT NULL COMMENT '模型名称',
  `style` varchar(20) DEFAULT NULL COMMENT '生成风格',
  `canvas_width` int DEFAULT NULL COMMENT '画布宽度',
  `canvas_height` int DEFAULT NULL COMMENT '画布高度',
  `prompt` text DEFAULT NULL COMMENT '用户提示词',
  `request_json` longtext DEFAULT NULL COMMENT '生成请求JSON',
  `generated_title` varchar(200) DEFAULT NULL COMMENT '生成大屏标题',
  `response_json` longtext DEFAULT NULL COMMENT '生成结果JSON',
  `validation_summary_json` longtext DEFAULT NULL COMMENT '前端校验摘要JSON',
  `status` varchar(32) NOT NULL DEFAULT 'success' COMMENT '状态：success/failed/parse_failed/stopped',
  `component_count` int NOT NULL DEFAULT 0 COMMENT '组件数量',
  `bound_count` int NOT NULL DEFAULT 0 COMMENT '动态绑定数量',
  `static_count` int NOT NULL DEFAULT 0 COMMENT '静态组件数量',
  `static_fallback_count` int NOT NULL DEFAULT 0 COMMENT '静态降级数量',
  `repaired_count` int NOT NULL DEFAULT 0 COMMENT '自动修复数量',
  `elapsed_ms` bigint DEFAULT NULL COMMENT '生成耗时毫秒',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '错误原因',
  `create_by` bigint DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ai_dashboard_record_user_time` (`tenant_id`, `user_id`, `create_time`),
  KEY `idx_ai_dashboard_record_business` (`tenant_id`, `business_definition_id`, `create_time`),
  KEY `idx_ai_dashboard_record_project` (`tenant_id`, `project_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI大屏生成记录';

CREATE TABLE IF NOT EXISTS `ai_dashboard_component_lineage` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `record_id` bigint NOT NULL COMMENT '生成记录ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `session_id` varchar(80) DEFAULT NULL COMMENT 'AI会话ID',
  `project_id` bigint DEFAULT NULL COMMENT '大屏项目ID',
  `project_name` varchar(128) DEFAULT NULL COMMENT '大屏项目名称',
  `business_definition_id` bigint DEFAULT NULL COMMENT '业务定义ID',
  `business_name` varchar(128) DEFAULT NULL COMMENT '业务定义名称',
  `component_index` int DEFAULT NULL COMMENT '组件序号',
  `component_key` varchar(100) DEFAULT NULL COMMENT '组件Key',
  `component_title` varchar(200) DEFAULT NULL COMMENT '组件标题',
  `dataset_id` bigint NOT NULL COMMENT '数据集ID',
  `dataset_name` varchar(128) DEFAULT NULL COMMENT '数据集名称',
  `field_names` varchar(2000) DEFAULT NULL COMMENT '使用字段，逗号分隔',
  `binding_status` varchar(32) DEFAULT NULL COMMENT '绑定状态',
  `create_by` bigint DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ai_dashboard_lineage_dataset` (`tenant_id`, `dataset_id`, `create_time`),
  KEY `idx_ai_dashboard_lineage_record` (`tenant_id`, `record_id`),
  KEY `idx_ai_dashboard_lineage_project` (`tenant_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI大屏组件数据资产血缘';
